/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.orbitix.vista;

import com.mycompany.orbitix.modelo.*;
import com.mycompany.orbitix.controlador.PasajeControlador;
import java.util.*;
import javax.swing.*;

/**
 * Vista de Registro de Pasajeros - Orbitix
 * @author karla (Modificado)
 */
public class VistaRegistroPasajero extends javax.swing.JDialog {

    private List<String> asientos;
    private Vuelo vuelo;
    private int indiceActual = 0;
    private List<Pasaje> pasajesRegistrados = new ArrayList<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaRegistroPasajero.class.getName());
    private Usuario usuarioLogueado;
    
    private boolean esNombreValido(String texto) {
    return texto != null && texto.matches("^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ ]+$");
}

    private boolean esNumero10Digitos(String texto) {
        return texto != null && texto.matches("^\\d{10}$");
    }

    private boolean esEdadValida(String texto) {
        return texto != null && texto.matches("^\\d+$");
    }

    private boolean esEmailValido(String texto) {
        return texto != null && texto.matches("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$");
    }


public VistaRegistroPasajero(java.awt.Frame parent, Vuelo vuelo, List<String> asientos, boolean modal, Usuario usuario) {
        super(parent, modal);
        this.vuelo = vuelo;
        this.asientos = asientos;
        this.usuarioLogueado = usuario; // Ahora 'usuario' sí existe como parámetro

        Fondo fondo = new Fondo("/recursos/fondo_VPrincipal_orbitix.png");
        fondo.setLayout(new java.awt.BorderLayout());

        initComponents(); 
        
        
        configurarComboBox();
        configurarDiseno();
        
        if (panelPrincipal != null) {
            panelPrincipal.setOpaque(false);
            fondo.add(panelPrincipal, java.awt.BorderLayout.CENTER);
        }

        setContentPane(fondo);
        this.setSize(1000, 700);
        this.setLocationRelativeTo(null);

        if (asientos == null || asientos.isEmpty()) {
            JOptionPane.showMessageDialog(parent, "Error: no se recibieron asientos seleccionados", "Error", JOptionPane.ERROR_MESSAGE);
            dispose();
            return;
        }

        cargarDatosVuelo();
        actualizarInterfaz();
    }

    private void configurarComboBox() {
        CBEquipaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "Artículo personal",
            "Maleta de mano",
            "Maleta de Bodega"
        }));
    }

    private void configurarDiseno() {
        panelPrincipal.setOpaque(false);
        jPanel2.setOpaque(false);
        jPanel3.setOpaque(false);
    }

    private void cargarDatosVuelo() {
        if (vuelo != null && vuelo.getRuta() != null) {
            lblInfoVuelo.setText("Vuelo: " + vuelo.getCodigo());
            lblInfoOrigen.setText("Origen: " + vuelo.getRuta().getOrigen());
            lblInfoDestino.setText("Destino: " + vuelo.getRuta().getDestino());
        }
    }

    private void actualizarInterfaz() {
        if (asientos == null || asientos.isEmpty()) {
            lblAsiento.setText("No hay asientos");
            return;
        }

        lblAsiento.setText("Asiento: " + asientos.get(indiceActual));

       
        txtNombre.setText("");
        txtApellido.setText("");
        txtCedula.setText("");
        txtTelefono.setText("");
        txtEmail.setText("");
        txtEdad.setText("");
        CBEquipaje.setSelectedIndex(0);

        btnAnterior.setEnabled(indiceActual > 0);
        btnSiguiente.setText(indiceActual == asientos.size() - 1 ? "FINALIZAR COMPRA" : "SIGUIENTE");
    }

private void finalizarVenta() {
    PasajeControlador control = new PasajeControlador();
    // 'pasajesRegistrados' es List<Pasaje>
    boolean exito = control.registrarVentaTotal(pasajesRegistrados);
    
    if (exito) {
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        
        // Esta línea dará error HASTA que modifiques el constructor de VistaCompra
        VistaCompra vistaPago = new VistaCompra(parentFrame, vuelo, pasajesRegistrados, usuarioLogueado);
        
        vistaPago.setVisible(true);
        this.dispose();
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblAsiento = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CBEquipaje = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        lblInfoOrigen = new javax.swing.JLabel();
        lblInfoVuelo = new javax.swing.JLabel();
        lblInfoDestino = new javax.swing.JLabel();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(153, 0, 153));
        panelPrincipal.setToolTipText("");
        panelPrincipal.setPreferredSize(new java.awt.Dimension(1360, 677));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de Pasajeros");

        lblAsiento.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAsiento.setForeground(new java.awt.Color(255, 255, 255));
        lblAsiento.setText("Asiento:");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Teléfono:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cédula:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Edad:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Equipaje:");

        CBEquipaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBEquipaje.setSelectedItem(CBEquipaje);
        CBEquipaje.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CBEquipaje.setDoubleBuffered(true);
        CBEquipaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBEquipajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(txtNombre)
                            .addComponent(txtApellido)
                            .addComponent(txtCedula)
                            .addComponent(txtTelefono)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEdad, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(CBEquipaje, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(65, 65, 65))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CBEquipaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.setOpaque(false);

        lblInfoOrigen.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblInfoOrigen.setForeground(new java.awt.Color(255, 255, 255));
        lblInfoOrigen.setText("Origen:");

        lblInfoVuelo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblInfoVuelo.setForeground(new java.awt.Color(255, 255, 255));
        lblInfoVuelo.setText("Vuelo:");

        lblInfoDestino.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblInfoDestino.setForeground(new java.awt.Color(255, 255, 255));
        lblInfoDestino.setText("Destino:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInfoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInfoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInfoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblInfoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblInfoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblInfoDestino)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAnterior.setBackground(new java.awt.Color(153, 0, 255));
        btnAnterior.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAnterior.setForeground(new java.awt.Color(255, 255, 255));
        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setBackground(new java.awt.Color(153, 0, 255));
        btnSiguiente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(457, 457, 457)
                        .addComponent(lblAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel1)))
                .addContainerGap(391, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAsiento)
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        if (indiceActual > 0) {
                indiceActual--;
                actualizarInterfaz();

                Pasaje p = pasajesRegistrados.get(indiceActual);


                txtNombre.setText(p.getPasajero().getNombre());
                txtApellido.setText(p.getPasajero().getApellido());
                txtCedula.setText(p.getPasajero().getCedula());
                txtTelefono.setText(p.getPasajero().getTelefono());
                txtEmail.setText(p.getPasajero().getEmail());
                txtEdad.setText(String.valueOf(p.getPasajero().getEdad()));

                TipoEquipaje tipo = p.getEquipaje().getTipo();
                if (tipo == TipoEquipaje.MALETA_MANO) CBEquipaje.setSelectedItem("Maleta de mano");
                else if (tipo == TipoEquipaje.MALETA_BODEGA) CBEquipaje.setSelectedItem("Maleta de Bodega");
                else CBEquipaje.setSelectedItem("Artículo personal");
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
                                        
        try {

            String nombre = txtNombre.getText().trim();
            String apellido = txtApellido.getText().trim();
            String cedula = txtCedula.getText().trim();
            String telefono = txtTelefono.getText().trim();
            String email = txtEmail.getText().trim();
            String edadStr = txtEdad.getText().trim();
            String textoEquipaje = CBEquipaje.getSelectedItem().toString();

            if (nombre.isEmpty() || apellido.isEmpty() || cedula.isEmpty() || edadStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, complete los campos obligatorios.");
                return;
            }

            if (!esNombreValido(nombre)) {
                JOptionPane.showMessageDialog(this, "El nombre solo debe contener letras.");
                txtNombre.requestFocus();
                return;
            }

            if (!esNombreValido(apellido)) {
               JOptionPane.showMessageDialog(this, "El apellido solo debe contener letras.");
               txtApellido.requestFocus();
               return;
            }

            if (!esNumero10Digitos(cedula)) {
               JOptionPane.showMessageDialog(this, "La cédula debe tener 10 dígitos.");
               txtCedula.requestFocus();
               return;
            }


            if (!esNumero10Digitos(telefono)) {
               JOptionPane.showMessageDialog(this, "El celular debe tener 10 dígitos.");
               txtTelefono.requestFocus();
               return;
            }

            if (!esEmailValido(email)) {
               JOptionPane.showMessageDialog(this, "Correo inválido. Debe ser por ejemplo: user@gmail.com");
               txtEmail.requestFocus();
               return;
            }

            if (!esEdadValida(edadStr)) {
               JOptionPane.showMessageDialog(this, "La edad solo debe contener números.");
               txtEdad.requestFocus();
               return;
            }

            int edad = Integer.parseInt(edadStr);
            Pasajero pasajero = new Pasajero(cedula, nombre, apellido, telefono, email, edad);


            TipoEquipaje tipoEnum;
            if (textoEquipaje.equals("Maleta de mano")) tipoEnum = TipoEquipaje.MALETA_MANO;
            else if (textoEquipaje.equals("Maleta de Bodega")) tipoEnum = TipoEquipaje.MALETA_BODEGA;
            else tipoEnum = TipoEquipaje.ARTICULO_PERSONAL;

            Equipaje objetoEquipaje = new Equipaje(tipoEnum);


            String codigoTkt = "TKT-" + System.currentTimeMillis() + "-" + (indiceActual + 1);


            Pasaje p = new Pasaje(codigoTkt, vuelo.getPrecio(), asientos.get(indiceActual), 
                                  ClaseAsiento.ECONOMICA, pasajero, vuelo, objetoEquipaje);


            if (indiceActual < pasajesRegistrados.size()) {
                pasajesRegistrados.set(indiceActual, p);
            } else {
                pasajesRegistrados.add(p);
            }


            if (indiceActual < asientos.size() - 1) {
                indiceActual++;
                actualizarInterfaz();
            } else {
                finalizarVenta();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La edad debe ser un número válido.");
    }

    
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void CBEquipajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBEquipajeActionPerformed

    }//GEN-LAST:event_CBEquipajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
java.awt.EventQueue.invokeLater(new Runnable() {
    @Override
    public void run() {
        Vuelo vuelo = new Vuelo(); 
        List<String> asientos = new java.util.ArrayList<>();
        
        // Creamos un usuario ficticio o nulo para que el constructor acepte la llamada
        com.mycompany.orbitix.modelo.Usuario usuarioDummy = null; 

        // Agregamos el 5to parámetro al final
        VistaRegistroPasajero dialog = new VistaRegistroPasajero(
            new javax.swing.JFrame(),
            vuelo,
            asientos,
            true,
            usuarioDummy // <--- ESTE ES EL 5TO PARÁMETRO QUE FALTABA
        );

        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
            }
        });
        dialog.setVisible(true);   }
});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBEquipaje;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAsiento;
    private javax.swing.JLabel lblInfoDestino;
    private javax.swing.JLabel lblInfoOrigen;
    private javax.swing.JLabel lblInfoVuelo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables


}

