/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.orbitix.vista;

import com.mycompany.orbitix.controlador.InicioControlador;
import com.mycompany.orbitix.controlador.LoginControlador;
import com.mycompany.orbitix.controlador.UsuarioControlador;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class VistaRegistro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaRegistro.class.getName());

  public VistaRegistro() {
    initComponents();

    txtusuario1LOG.setText("Ejemplo: usuario@correo.com");
    txtNombre.setText(""); 

   
    txtusuario1LOG.setForeground(java.awt.Color.GRAY);

   
    txtusuario1LOG.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (txtusuario1LOG.getText().equals("Ejemplo: usuario@correo.com")) {
                txtusuario1LOG.setText("");
                txtusuario1LOG.setForeground(java.awt.Color.BLACK);
            }
        }
        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (txtusuario1LOG.getText().isEmpty()) {
                txtusuario1LOG.setForeground(java.awt.Color.GRAY);
                txtusuario1LOG.setText("Ejemplo: usuario@correo.com");
            }
        }
    });
    
    Fondo fondo = new Fondo("/recursos/fondo_login_orbitix.png");
    fondo.setLayout(new java.awt.BorderLayout());
    setContentPane(fondo);

    panelRegistro.setOpaque(false); 
    fondo.add(panelRegistro, java.awt.BorderLayout.CENTER);

    setExtendedState(JFrame.MAXIMIZED_BOTH);
    setLocationRelativeTo(null);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegistro = new javax.swing.JPanel();
        labelregistro = new javax.swing.JLabel();
        labelcorreoLOG = new javax.swing.JLabel();
        txtusuario1LOG = new javax.swing.JTextField();
        LOG = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        btnVolverLOG = new javax.swing.JButton();
        LOGCedula = new javax.swing.JLabel();
        LoGNombre = new javax.swing.JLabel();
        txtusuario1LOG1 = new javax.swing.JTextField();
        txtcontra1 = new javax.swing.JPasswordField();
        txtNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelRegistro.setPreferredSize(new java.awt.Dimension(1360, 677));

        labelregistro.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        labelregistro.setForeground(new java.awt.Color(255, 255, 255));
        labelregistro.setText("    CREAR CUENTA");

        labelcorreoLOG.setBackground(new java.awt.Color(153, 0, 255));
        labelcorreoLOG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelcorreoLOG.setForeground(new java.awt.Color(255, 255, 255));
        labelcorreoLOG.setText("                Correo");
        labelcorreoLOG.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        LOG.setBackground(new java.awt.Color(153, 0, 255));
        LOG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LOG.setForeground(new java.awt.Color(255, 255, 255));
        LOG.setText("                Contraseña");
        LOG.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        btnguardar.setBackground(new java.awt.Color(51, 204, 255));
        btnguardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setText("GUARDAR Y REGISTRAR");
        btnguardar.addActionListener(this::btnguardarActionPerformed);

        btnVolverLOG.setBackground(new java.awt.Color(51, 204, 255));
        btnVolverLOG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolverLOG.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverLOG.setText("VOLVER");
        btnVolverLOG.addActionListener(this::btnVolverLOGActionPerformed);

        LOGCedula.setBackground(new java.awt.Color(153, 0, 255));
        LOGCedula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LOGCedula.setForeground(new java.awt.Color(255, 255, 255));
        LOGCedula.setText("                Cédula");
        LOGCedula.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        LoGNombre.setBackground(new java.awt.Color(153, 0, 255));
        LoGNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LoGNombre.setForeground(new java.awt.Color(255, 255, 255));
        LoGNombre.setText("                Nombre");
        LoGNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        txtusuario1LOG1.addActionListener(this::txtusuario1LOG1ActionPerformed);

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        javax.swing.GroupLayout panelRegistroLayout = new javax.swing.GroupLayout(panelRegistro);
        panelRegistro.setLayout(panelRegistroLayout);
        panelRegistroLayout.setHorizontalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistroLayout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRegistroLayout.createSequentialGroup()
                                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtusuario1LOG, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LOG, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcontra1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(114, 114, 114)
                                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRegistroLayout.createSequentialGroup()
                                        .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LoGNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(101, 101, 101)
                                        .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnVolverLOG, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtusuario1LOG1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelRegistroLayout.createSequentialGroup()
                                .addComponent(labelcorreoLOG, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(174, 174, 174)
                                .addComponent(LOGCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelRegistroLayout.createSequentialGroup()
                        .addGap(442, 442, 442)
                        .addComponent(labelregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        panelRegistroLayout.setVerticalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistroLayout.createSequentialGroup()
                .addContainerGap(359, Short.MAX_VALUE)
                .addComponent(labelregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRegistroLayout.createSequentialGroup()
                        .addComponent(btnguardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnVolverLOG)
                        .addGap(72, 72, 72))
                    .addGroup(panelRegistroLayout.createSequentialGroup()
                        .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelcorreoLOG, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LOGCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtusuario1LOG, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtusuario1LOG1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LOG, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LoGNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcontra1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed

        String email = txtusuario1LOG.getText().trim();
        String cedula = txtusuario1LOG1.getText().trim();
        String nombre = new String(txtNombre.getText()).trim(); 
        String pass = new String(txtcontra1.getPassword()).trim();

        UsuarioControlador control = new UsuarioControlador();

        if (email.isEmpty() || cedula.isEmpty() || nombre.isEmpty() || pass.isEmpty()
                || email.equals("Ejemplo: usuario@correo.com")) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
            return;
        }

        if (!email.contains("@") || !email.contains(".")) {
            JOptionPane.showMessageDialog(this,
                    "El formato del correo es incorrecto.\nDebe ser tipo: usuario@correo.com",
                    "Formato Inválido",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (control.existeCorreo(email)) {
            JOptionPane.showMessageDialog(this, "Este correo ya está registrado.");
            return;
        }

        if (control.registrar(cedula, nombre, email, pass)) {
            JOptionPane.showMessageDialog(this, "¡Cuenta creada exitosamente!");
            VistaLogin login = new VistaLogin();
            new LoginControlador(login); 
            login.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Hubo un error al guardar los datos.");
        }

    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnVolverLOGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverLOGActionPerformed
        VistaInicio inicio = new VistaInicio();
        new InicioControlador(inicio); 
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverLOGActionPerformed

    private void txtusuario1LOG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuario1LOG1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuario1LOG1ActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaRegistro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOG;
    private javax.swing.JLabel LOGCedula;
    private javax.swing.JLabel LoGNombre;
    private javax.swing.JButton btnVolverLOG;
    private javax.swing.JButton btnguardar;
    private javax.swing.JLabel labelcorreoLOG;
    private javax.swing.JLabel labelregistro;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtcontra1;
    private javax.swing.JTextField txtusuario1LOG;
    private javax.swing.JTextField txtusuario1LOG1;
    // End of variables declaration//GEN-END:variables
}
