/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.orbitix.vista;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class VistaFacturacion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaFacturacion.class.getName());
    private java.util.List<com.mycompany.orbitix.modelo.Pasaje> pasajes;
    /**
     * Creates new form VistaFacturacion
     */
    public VistaFacturacion() {
        initComponents();
        Fondo fondo = new Fondo("/recursos/fondo_vPrincipal_orbitix.png");
        fondo.setLayout(new java.awt.BorderLayout());
        setContentPane(fondo);
        panelFacturacion.setOpaque(false); 
        fondo.add(panelFacturacion, java.awt.BorderLayout.CENTER);
         

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        
    }
    
    public VistaFacturacion(java.util.List<com.mycompany.orbitix.modelo.Pasaje> pasajes) {
    this();
    this.pasajes = pasajes;
    }
    
    public JButton getBtnImprimirFactura() {
        return btnImprimirFactura;
    }

    public JButton getBtnImprimirTicket() {
        return btnImprimirTicket;
    }

    public JButton getBtnContinuarCompra() {
        return btnContinuarCompra;
    }

    public void addBtnImprimirFacturaListener(ActionListener listener) {
        btnImprimirFactura.addActionListener(listener);
    }
    
    public void addBtnImprimirTicketListener(ActionListener listener) {
        btnImprimirTicket.addActionListener(listener);
    }
    
    public void addBtnContinuarCompraListener(ActionListener listener) {
        btnContinuarCompra.addActionListener(listener);
    }
    
    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFacturacion = new javax.swing.JPanel();
        laberagradecimiento = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnImprimirFactura = new javax.swing.JButton();
        btnImprimirTicket = new javax.swing.JButton();
        btnContinuarCompra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFacturacion.setBackground(new java.awt.Color(153, 0, 153));
        panelFacturacion.setPreferredSize(new java.awt.Dimension(1360, 677));

        laberagradecimiento.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        laberagradecimiento.setForeground(new java.awt.Color(255, 255, 255));
        laberagradecimiento.setText("GRACIAS POR SU COMPRA!");

        panelBotones.setBackground(new java.awt.Color(51, 0, 102));

        btnImprimirFactura.setBackground(new java.awt.Color(102, 0, 102));
        btnImprimirFactura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnImprimirFactura.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimirFactura.setText("Imprimir Factura");
        btnImprimirFactura.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnImprimirFactura.addActionListener(this::btnImprimirFacturaActionPerformed);

        btnImprimirTicket.setBackground(new java.awt.Color(102, 0, 102));
        btnImprimirTicket.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnImprimirTicket.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimirTicket.setText("Imprimir Ticket");
        btnImprimirTicket.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnImprimirTicket.addActionListener(this::btnImprimirTicketActionPerformed);

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnImprimirTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimirFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnImprimirFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnImprimirTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        btnContinuarCompra.setBackground(new java.awt.Color(102, 0, 102));
        btnContinuarCompra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnContinuarCompra.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuarCompra.setText("Continuar Comprando");
        btnContinuarCompra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnContinuarCompra.addActionListener(this::btnContinuarCompraActionPerformed);

        javax.swing.GroupLayout panelFacturacionLayout = new javax.swing.GroupLayout(panelFacturacion);
        panelFacturacion.setLayout(panelFacturacionLayout);
        panelFacturacionLayout.setHorizontalGroup(
            panelFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFacturacionLayout.createSequentialGroup()
                .addContainerGap(404, Short.MAX_VALUE)
                .addComponent(laberagradecimiento)
                .addGap(329, 329, 329))
            .addGroup(panelFacturacionLayout.createSequentialGroup()
                .addGroup(panelFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFacturacionLayout.createSequentialGroup()
                        .addGap(511, 511, 511)
                        .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFacturacionLayout.createSequentialGroup()
                        .addGap(560, 560, 560)
                        .addComponent(btnContinuarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFacturacionLayout.setVerticalGroup(
            panelFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFacturacionLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(laberagradecimiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnContinuarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirFacturaActionPerformed

    private void btnImprimirTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirTicketActionPerformed

        StringBuilder sb = new StringBuilder();
        for (com.mycompany.orbitix.modelo.Pasaje p : pasajes) {
            sb.append(com.mycompany.orbitix.util.Ticket.generarBoardingPass(p)).append("\n");
        }

        javax.swing.JTextArea area = new javax.swing.JTextArea(sb.toString(), 25, 60);
        area.setEditable(false);
        javax.swing.JOptionPane.showMessageDialog(this, new javax.swing.JScrollPane(area),
                "Ticket(s) de vuelo", javax.swing.JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnImprimirTicketActionPerformed

    private void btnContinuarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContinuarCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaFacturacion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuarCompra;
    private javax.swing.JButton btnImprimirFactura;
    private javax.swing.JButton btnImprimirTicket;
    private javax.swing.JLabel laberagradecimiento;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelFacturacion;
    // End of variables declaration//GEN-END:variables
}
