/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.orbitix.vista;

import com.mycompany.orbitix.datos.RepositorioArchivos;
import com.mycompany.orbitix.modelo.Usuario;
import com.mycompany.orbitix.modelo.Vuelo;
import java.util.List;
import javax.swing.JFrame;
import java.util.logging.Logger;
import com.github.lgooddatepicker.components.DatePicker;
import com.github.lgooddatepicker.components.DatePickerSettings;


/**
 *
 * @author USUARIO
 */
public class VistaPrincipal extends javax.swing.JFrame {
    private DatePicker datePicker;
    private static final Logger logger =
    Logger.getLogger(VistaPrincipal.class.getName());
    public Usuario usuarioLogueado;
    public List<Vuelo> listaVuelosActuales;
    public RepositorioArchivos repo = new RepositorioArchivos();

   
    public VistaPrincipal() {
    initComponents();
     
    configurarTabla(); 
    llenarCombosDinamicos();
    
    Fondo fondo = new Fondo("/recursos/fondo_VPrincipal_orbitix.png");
    fondo.setLayout(new java.awt.BorderLayout());
    setContentPane(fondo);

    panelPrincipal.setOpaque(false); 
    fondo.add(panelPrincipal, java.awt.BorderLayout.CENTER);

    setExtendedState(JFrame.MAXIMIZED_BOTH);
    setLocationRelativeTo(null);

    }
    
    public VistaPrincipal(Usuario usuario) {
        this();
        this.usuarioLogueado = usuario;

       
        DatePickerSettings settings = new DatePickerSettings();
        settings.setFormatForDatesCommonEra("dd/MM/yyyy");
        settings.setAllowKeyboardEditing(false);

        datePicker = new DatePicker(settings);
        datePicker.setBounds(55, 420, 220, 35); 
        panelPrincipal.add(datePicker);


        if (usuario != null) {
            labelsaludo.setText("Hola, " + usuario.getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        labelsaludo = new javax.swing.JLabel();
        labelvenco1 = new javax.swing.JLabel();
        labelorigen1 = new javax.swing.JLabel();
        btnBuscarVuelos = new javax.swing.JButton();
        cbselorigen = new javax.swing.JComboBox<>();
        cbseldestino = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVuelos = new javax.swing.JTable();
        btnSelecComprar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        labeldestino1 = new javax.swing.JLabel();
        labeldestino2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1360, 677));

        panelPrincipal.setBackground(new java.awt.Color(51, 0, 51));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(1360, 677));

        labelsaludo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        labelsaludo.setForeground(new java.awt.Color(255, 255, 255));
        labelsaludo.setText("           Hola, Usuario");

        labelvenco1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelvenco1.setForeground(new java.awt.Color(255, 255, 255));
        labelvenco1.setText("Vuelos Encontrados");

        labelorigen1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelorigen1.setForeground(new java.awt.Color(255, 255, 255));
        labelorigen1.setText("Origen:");

        btnBuscarVuelos.setBackground(new java.awt.Color(153, 0, 255));
        btnBuscarVuelos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarVuelos.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarVuelos.setText("BUSCAR VUELOS");
        btnBuscarVuelos.addActionListener(this::btnBuscarVuelosActionPerformed);

        cbselorigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbselorigen.addActionListener(this::cbselorigenActionPerformed);

        cbseldestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbseldestino.addActionListener(this::cbseldestinoActionPerformed);

        tablaVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaVuelos);

        btnSelecComprar.setBackground(new java.awt.Color(153, 0, 255));
        btnSelecComprar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSelecComprar.setForeground(new java.awt.Color(255, 255, 255));
        btnSelecComprar.setText("SELECCIONAR");
        btnSelecComprar.addActionListener(this::btnSelecComprarActionPerformed);

        btnSalir.setBackground(new java.awt.Color(153, 0, 255));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        labeldestino1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labeldestino1.setForeground(new java.awt.Color(255, 255, 255));
        labeldestino1.setText("Destino:");

        labeldestino2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labeldestino2.setForeground(new java.awt.Color(255, 255, 255));
        labeldestino2.setText("Fecha:");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(labelsaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(btnSalir))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(labelorigen1)
                                .addGap(249, 249, 249)
                                .addComponent(labelvenco1))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscarVuelos)
                                    .addComponent(cbseldestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbselorigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labeldestino1)
                                    .addComponent(labeldestino2))
                                .addGap(193, 193, 193)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(533, 533, 533)
                        .addComponent(btnSelecComprar)))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnSalir)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelsaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelorigen1)
                    .addComponent(labelvenco1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cbselorigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(labeldestino1)
                        .addGap(33, 33, 33)
                        .addComponent(cbseldestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(labeldestino2)
                        .addGap(150, 150, 150)
                        .addComponent(btnBuscarVuelos))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(btnSelecComprar)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 563, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbselorigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbselorigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbselorigenActionPerformed

    private void cbseldestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbseldestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbseldestinoActionPerformed

    private void btnBuscarVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVuelosActionPerformed
    
    }//GEN-LAST:event_btnBuscarVuelosActionPerformed

    private void btnSelecComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecComprarActionPerformed

    }//GEN-LAST:event_btnSelecComprarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarVuelos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSelecComprar;
    private javax.swing.JComboBox<String> cbseldestino;
    private javax.swing.JComboBox<String> cbselorigen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labeldestino1;
    private javax.swing.JLabel labeldestino2;
    private javax.swing.JLabel labelorigen1;
    private javax.swing.JLabel labelsaludo;
    private javax.swing.JLabel labelvenco1;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tablaVuelos;
    // End of variables declaration//GEN-END:variables
 public javax.swing.JButton getBtnBuscarVuelos() {
        return btnBuscarVuelos;
    }

    public javax.swing.JButton getBtnSelecComprar() {
        return btnSelecComprar;
    }

    public javax.swing.JButton getBtnSalir() {
        return btnSalir;
    }

    public javax.swing.JComboBox<String> getCbselorigen() {
        return cbselorigen;
    }

    public javax.swing.JComboBox<String> getCbseldestino() {
        return cbseldestino;
    }

    public javax.swing.JTable getTablaVuelos() {
        return tablaVuelos;
    }

    public DatePicker getDatePicker() {
    return datePicker;
    }
    
    public void configurarTabla() {
        javax.swing.table.DefaultTableModel modelo =
                new javax.swing.table.DefaultTableModel(
                        new Object[][]{},
                        new String[]{"Código", "Fecha", "Ruta", "Precio", "Duración", "Disponibles"}
                ) {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }
                };
        tablaVuelos.setModel(modelo);
    }

    public void llenarCombosDinamicos() {
        cbselorigen.removeAllItems();
        cbseldestino.removeAllItems();

        listaVuelosActuales = repo.cargarVuelos();

        java.util.Set<String> origenes = new java.util.HashSet<>();
        java.util.Set<String> destinos = new java.util.HashSet<>();

        for (Vuelo v : listaVuelosActuales) {
            origenes.add(v.getRuta().getOrigen());
            destinos.add(v.getRuta().getDestino());
        }

        for (String o : origenes) cbselorigen.addItem(o);
        for (String d : destinos) cbseldestino.addItem(d);
    }

}
